"""Build and send the daily HTML immigration intelligence report via Gmail."""
import logging
import os
import smtplib
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from .classifier import ClassifiedItem, VISA_CATEGORIES

logger = logging.getLogger(__name__)

IMPACT_COLORS = {
    "High": "#d32f2f",
    "Medium": "#f57c00",
    "Low": "#388e3c",
    "None": "#9e9e9e",
}

IMPACT_BADGE = {
    k: f'<span style="background:{c};color:#fff;padding:2px 8px;border-radius:4px;font-size:12px;font-weight:bold">{k}</span>'
    for k, c in IMPACT_COLORS.items()
}


def _badge(level: str) -> str:
    return IMPACT_BADGE.get(level, IMPACT_BADGE["None"])


def build_html_report(items: list[ClassifiedItem], run_date: str) -> str:
    high_priority = [i for i in items if i.max_impact == "High"]
    action_items = [i for i in items if i.action_required]

    # Group by affected category
    by_category: dict[str, list[ClassifiedItem]] = {c: [] for c in VISA_CATEGORIES}
    for item in items:
        for cat in item.affected_categories:
            if cat in by_category:
                by_category[cat].append(item)

    def item_card(item: ClassifiedItem) -> str:
        impact_row = " ".join(
            f'{cat}: {_badge(level)}'
            for cat, level in item.impact.items()
            if level != "None"
        )
        action_flag = (
            '<div style="margin-top:6px;color:#b71c1c;font-weight:bold">⚠️ Action may be required</div>'
            if item.action_required else ""
        )
        return f"""
        <div style="border:1px solid #e0e0e0;border-radius:8px;padding:16px;margin-bottom:12px;background:#fafafa">
          <div style="font-size:13px;color:#757575;margin-bottom:4px">{item.source}</div>
          <a href="{item.url}" style="font-size:16px;font-weight:bold;color:#1565c0;text-decoration:none">{item.title}</a>
          <p style="margin:10px 0;color:#212121;line-height:1.6">{item.summary}</p>
          <div style="font-size:13px">{impact_row}</div>
          {action_flag}
        </div>"""

    category_sections = ""
    for cat, cat_items in by_category.items():
        if not cat_items:
            continue
        cards = "".join(item_card(i) for i in cat_items)
        category_sections += f"""
        <h2 style="color:#1a237e;border-bottom:2px solid #3f51b5;padding-bottom:6px">{cat}</h2>
        {cards}"""

    if not category_sections:
        category_sections = "<p style='color:#757575'>No significant updates detected today.</p>"

    high_priority_list = "".join(
        f'<li><a href="{i.url}">{i.title}</a> — {i.source}</li>'
        for i in high_priority
    )
    if high_priority_list:
        high_priority_section = f"""
        <div style="background:#ffebee;border:1px solid #ef9a9a;border-radius:8px;padding:16px;margin-bottom:24px">
          <h3 style="color:#c62828;margin-top:0">🚨 High Priority Updates ({len(high_priority)})</h3>
          <ul>{high_priority_list}</ul>
        </div>"""
    else:
        high_priority_section = ""

    return f"""<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="font-family:Arial,sans-serif;max-width:700px;margin:0 auto;padding:20px;color:#212121">
  <div style="background:linear-gradient(135deg,#1a237e,#283593);color:#fff;padding:24px;border-radius:8px;margin-bottom:24px">
    <h1 style="margin:0;font-size:22px">🇺🇸 Immigration Intelligence Report</h1>
    <p style="margin:8px 0 0;opacity:0.85">{run_date} | {len(items)} new/updated items detected</p>
  </div>

  {high_priority_section}

  <div style="background:#e8eaf6;border-radius:8px;padding:16px;margin-bottom:24px">
    <strong>Summary:</strong> {len(items)} updates across USCIS, SEVP, State Dept, and Federal Register.
    {len(action_items)} items may require immediate attention.
  </div>

  {category_sections}

  <hr style="margin:32px 0;border:none;border-top:1px solid #e0e0e0">
  <p style="font-size:12px;color:#9e9e9e">
    Generated by Immigration Intelligence Agent &nbsp;|&nbsp;
    Sources: USCIS, SEVP, State Department, Federal Register &nbsp;|&nbsp;
    Powered by Claude AI
  </p>
</body>
</html>"""


def send_report(html_body: str, run_date: str, item_count: int) -> bool:
    gmail_user = os.environ.get("GMAIL_FROM", "rafshakirat@gmail.com")
    gmail_to = os.environ.get("GMAIL_TO", "rafshakirat@gmail.com")
    app_password = os.environ.get("GMAIL_APP_PASSWORD")

    if not app_password:
        logger.error("GMAIL_APP_PASSWORD not set — skipping email")
        return False

    subject = f"[Immigration Intel] Daily Report - {run_date} ({item_count} updates)"
    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = gmail_user
    msg["To"] = gmail_to
    msg.attach(MIMEText(html_body, "html", "utf-8"))

    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(gmail_user, app_password)
            server.sendmail(gmail_user, gmail_to, msg.as_bytes())
        logger.info("Report emailed to %s", gmail_to)
        return True
    except Exception as exc:
        logger.error("Failed to send email: %s", exc)
        return False
